package JFrame;

import Dao.DichVuDao;
import Dao.HoaDonChiTietDao;
import Dao.NguoiDungDao;
import Dao.NhatKiHeThongDao;
import Dao.NhatKiTaiKhoanDao;
import Dao.QuanLyMayDao;
import Data.DichVu;
import Data.HoaDonChiTiet;
import Data.NguoiDung;
import Data.NhatKiTaiKhoan;
import Data.NhatKiHeThong;
import Data.QuanLyMay;
import Dialog.DangNhapDiaLog;
import Dialog.DichVuAdminDialog;
import Dialog.HoaDonDialog;
import Dialog.NguoiDungDialog;
import Library.Auth;
import Library.MessDiaLogHelper;
import Library.More;
import Library.Validator;
import java.awt.Color;
import java.awt.Desktop;
import java.net.URI;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public Admin() throws Exception {
        initComponents();
        init();

        More.jframAdd(this, "QUẢN LÝ QUÁN NET");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btnTinhTien = new javax.swing.JButton();
        btnNapTien = new javax.swing.JButton();
        btnMoMay = new javax.swing.JButton();
        btnTatMay = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblMayTram = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnThemNguoiDung = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnSuaNguoiDung = new javax.swing.JButton();
        btnXoaNguoiDung = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTimNguoiDung = new javax.swing.JTextField();
        btnTimNguoiDung = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNguoiDung = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNgayBdNkht = new javax.swing.JTextField();
        txtNgayKtNkht = new javax.swing.JTextField();
        btnRefreshNkht = new javax.swing.JButton();
        btnXoaNkht = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNkht = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNgayBdNktk = new javax.swing.JTextField();
        txtNgayKtNktk = new javax.swing.JTextField();
        btnRefreshNktk = new javax.swing.JButton();
        btnXoaNktk = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblNktk = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnThemDv = new javax.swing.JButton();
        btnSuaDv = new javax.swing.JButton();
        btnXoaDv = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTimDv = new javax.swing.JTextField();
        btnTimDv = new javax.swing.JButton();
        btnRefreshDv = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblDonHang = new javax.swing.JTable();
        btnHoanThanh = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mniMayTram = new javax.swing.JMenuItem();
        mniTaiKhoan = new javax.swing.JMenuItem();
        mniDangXuat = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mniNkht = new javax.swing.JMenuItem();
        mniNktk = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mniTroGiup = new javax.swing.JMenuItem();
        mniGioiThieu = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnTinhTien.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Dollar.png")); // NOI18N
        btnTinhTien.setText("Tính tiền");
        btnTinhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTienActionPerformed(evt);
            }
        });

        btnNapTien.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Euro.png")); // NOI18N
        btnNapTien.setText("Nạp tiền");
        btnNapTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNapTienActionPerformed(evt);
            }
        });

        btnMoMay.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Desktop.png")); // NOI18N
        btnMoMay.setText("Mở máy");
        btnMoMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoMayActionPerformed(evt);
            }
        });

        btnTatMay.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Lock.png")); // NOI18N
        btnTatMay.setText("Khoá máy");
        btnTatMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTatMayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMoMay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTatMay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTinhTien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNapTien)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTinhTien)
                    .addComponent(btnNapTien)
                    .addComponent(btnMoMay)
                    .addComponent(btnTatMay))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tblMayTram.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tblMayTram);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("Máy trạm", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnThemNguoiDung.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Add.png")); // NOI18N
        btnThemNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNguoiDungActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Refresh.png")); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnSuaNguoiDung.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Bookmark.png")); // NOI18N
        btnSuaNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNguoiDungActionPerformed(evt);
            }
        });

        btnXoaNguoiDung.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Delete.png")); // NOI18N
        btnXoaNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNguoiDungActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên người sử dụng:");

        btnTimNguoiDung.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Search.png")); // NOI18N
        btnTimNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimNguoiDungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemNguoiDung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSuaNguoiDung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoaNguoiDung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimNguoiDung)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemNguoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuaNguoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaNguoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTimNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(btnTimNguoiDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblNguoiDung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblNguoiDung);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("Người dùng", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Tên người sử dụng:");

        jButton14.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Search.png")); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Calendar.png")); // NOI18N
        jLabel4.setText("Kết thúc:");

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Calendar.png")); // NOI18N
        jLabel5.setText("Bắt đầu:");

        btnRefreshNkht.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Refresh.png")); // NOI18N
        btnRefreshNkht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshNkhtActionPerformed(evt);
            }
        });

        btnXoaNkht.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Delete.png")); // NOI18N
        btnXoaNkht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNkhtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgayBdNkht, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgayKtNkht, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefreshNkht)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(btnXoaNkht)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoaNkht, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRefreshNkht, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(txtNgayBdNkht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNgayKtNkht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton14))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tblNkht.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblNkht);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("Nhật kí hệ thống", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Tên người sử dụng:");

        jButton15.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Search.png")); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Calendar.png")); // NOI18N
        jLabel7.setText("Kết thúc:");

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Calendar.png")); // NOI18N
        jLabel8.setText("Bắt đầu:");

        btnRefreshNktk.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Refresh.png")); // NOI18N

        btnXoaNktk.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Delete.png")); // NOI18N
        btnXoaNktk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNktkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgayBdNktk, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgayKtNktk, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefreshNktk)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(btnXoaNktk)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoaNktk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRefreshNktk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(txtNgayBdNktk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNgayKtNktk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton15))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tblNktk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblNktk);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("Nhật kí tài khoản", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnThemDv.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Add.png")); // NOI18N
        btnThemDv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDvActionPerformed(evt);
            }
        });

        btnSuaDv.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Bookmark.png")); // NOI18N
        btnSuaDv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDvActionPerformed(evt);
            }
        });

        btnXoaDv.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Delete.png")); // NOI18N
        btnXoaDv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDvActionPerformed(evt);
            }
        });

        jLabel2.setText("Tìm dịch vụ:");

        btnTimDv.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Search.png")); // NOI18N
        btnTimDv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimDvActionPerformed(evt);
            }
        });

        btnRefreshDv.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Refresh.png")); // NOI18N
        btnRefreshDv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshDvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemDv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSuaDv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoaDv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefreshDv)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimDv, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimDv)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThemDv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuaDv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaDv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTimDv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(btnTimDv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRefreshDv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tblDichVu);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("Dịch vụ", jPanel5);

        tblDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tblDonHang);

        btnHoanThanh.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\tick.png")); // NOI18N
        btnHoanThanh.setText("Hoàn thành");
        btnHoanThanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoanThanhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHoanThanh)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHoanThanh)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabs.addTab("Đơn hàng", jPanel11);

        jMenuBar2.setMinimumSize(new java.awt.Dimension(239, 40));

        jMenu3.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Database.png")); // NOI18N
        jMenu3.setText("Quản lý");

        mniMayTram.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Computer.png")); // NOI18N
        mniMayTram.setText("Máy trạm");
        mniMayTram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniMayTramActionPerformed(evt);
            }
        });
        jMenu3.add(mniMayTram);

        mniTaiKhoan.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Clien list.png")); // NOI18N
        mniTaiKhoan.setText("Tài khoản");
        mniTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTaiKhoanActionPerformed(evt);
            }
        });
        jMenu3.add(mniTaiKhoan);

        mniDangXuat.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Log out.png")); // NOI18N
        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        jMenu3.add(mniDangXuat);

        jMenuBar2.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Report.png")); // NOI18N
        jMenu4.setText("Hệ thống");

        mniNkht.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\List.png")); // NOI18N
        mniNkht.setText("Nhật kí hệ thống");
        mniNkht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNkhtActionPerformed(evt);
            }
        });
        jMenu4.add(mniNkht);

        mniNktk.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Lists.png")); // NOI18N
        mniNktk.setText("Nhật kí tài khoản");
        mniNktk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNktkActionPerformed(evt);
            }
        });
        jMenu4.add(mniNktk);

        jMenuBar2.add(jMenu4);

        jMenu6.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Help.png")); // NOI18N
        jMenu6.setText("Giúp đỡ");

        mniTroGiup.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Info.png")); // NOI18N
        mniTroGiup.setText("Trợ giúp");
        jMenu6.add(mniTroGiup);

        mniGioiThieu.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Online.png")); // NOI18N
        mniGioiThieu.setText("Giới thiệu phần mềm");
        mniGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGioiThieuActionPerformed(evt);
            }
        });
        jMenu6.add(mniGioiThieu);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTaiKhoanActionPerformed
        tabs.setSelectedIndex(1);
    }//GEN-LAST:event_mniTaiKhoanActionPerformed

    private void mniGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGioiThieuActionPerformed
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.browse(new URI("https://senet.cloud/vi/"));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_mniGioiThieuActionPerformed

    private void btnTinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTienActionPerformed
        index = tblMayTram.getSelectedRow();
        if (index >= 0) {
            if (MessDiaLogHelper.showConfirmDiaLog(this, "Bạn muốn tính tiền " + getMa(index, tblMayTram), "Xác nhận") == 0) {
                try {
                    new HoaDonDialog(this, true, getMa(index, tblMayTram)).setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                    MessDiaLogHelper.showMessDiaLog(this, "Tính tiền thất bại", "Thông báo");
                }

            }
        } else {
            MessDiaLogHelper.showMessDiaLog(this, "Bạn cần chọn một máy trong bảng để tính tiền", "Thông báo");
        }
    }//GEN-LAST:event_btnTinhTienActionPerformed

    private void btnThemNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNguoiDungActionPerformed
        new NguoiDungDialog(this, true, false).setVisible(true);
    }//GEN-LAST:event_btnThemNguoiDungActionPerformed

    private void btnThemDvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDvActionPerformed
        new DichVuAdminDialog(this, true, false).setVisible(true);
    }//GEN-LAST:event_btnThemDvActionPerformed

    private void btnSuaDvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDvActionPerformed
        index = tblDichVu.getSelectedRow();
        if (index >= 0) {
            new DichVuAdminDialog(this, true, true, getMa(index, tblDichVu)).setVisible(true);
        } else {
            MessDiaLogHelper.showMessDiaLog(this, "Bạn cần chọn một hàng trong bảng để cập nhật", "Thông báo");
        }

    }//GEN-LAST:event_btnSuaDvActionPerformed

    private void btnXoaDvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDvActionPerformed
        index = tblDichVu.getSelectedRow();
        if (index >= 0) {
            if (MessDiaLogHelper.showConfirmDiaLog(this, "Bạn thực sự muốn xoá dịch vụ này?", "Xác nhận") == 0) {
                try {
                    DichVuDao dao = new DichVuDao();

                    dao.delete(getMa(index, tblDichVu));
                    fillTableDichVu(dvDao.selectAll());
                    MessDiaLogHelper.showMessDiaLog(this, "Xoá thành công", "Thông báo");
                } catch (Exception e) {
                    MessDiaLogHelper.showMessDiaLog(this, "Xoá thất bại", "Thông báo");
                }
            }
        } else {
            MessDiaLogHelper.showMessDiaLog(this, "Bạn cần chọn một hàng trong bảng để xoá", "Thông báo");
        }
    }//GEN-LAST:event_btnXoaDvActionPerformed

    private void btnTimDvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimDvActionPerformed
        try {
            if (txtTimDv == null) {
                fillTableDichVu(dvDao.selectAll());

            } else {
                fillTableDichVu(dvDao.searchByName(txtTimDv.getText()));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnTimDvActionPerformed

    private void btnSuaNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNguoiDungActionPerformed
        index = tblNguoiDung.getSelectedRow();
        if (index >= 0) {
            new NguoiDungDialog(this, true, true, getMa(index, tblNguoiDung)).setVisible(true);
        } else {
            MessDiaLogHelper.showMessDiaLog(this, "Bạn cần chọn một hàng trong bảng để cập nhật", "Thông báo");
        }

    }//GEN-LAST:event_btnSuaNguoiDungActionPerformed

    private void btnXoaNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNguoiDungActionPerformed
        index = tblNguoiDung.getSelectedRow();
        if (index >= 0) {
            if (MessDiaLogHelper.showConfirmDiaLog(this, "Bạn thực sự muốn xoá?", "Xác nhận") == 0) {
                try {
                    NguoiDungDao dao = new NguoiDungDao();

                    dao.delete(getMa(index, tblNguoiDung));
                    fillTableNguoiDung(ndDao.selectAll());
                    MessDiaLogHelper.showMessDiaLog(this, "Xoá thành công", "Thông báo");
                } catch (Exception e) {
                    MessDiaLogHelper.showMessDiaLog(this, "Xoá thất bại", "Thông báo");
                }
            }
        } else {
            MessDiaLogHelper.showMessDiaLog(this, "Bạn cần chọn một hàng trong bảng để xoá", "Thông báo");
        }
    }//GEN-LAST:event_btnXoaNguoiDungActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        try {
            fillTableNguoiDung(ndDao.selectAll());
        } catch (Exception ex) {
            ex.printStackTrace();
            MessDiaLogHelper.showErrorDiaLog(this, "Lỗi truy vấn", "Lỗi");
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnTimNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimNguoiDungActionPerformed
        try {
            if (txtTimNguoiDung == null) {
                fillTableNguoiDung(ndDao.selectAll());

            } else {
                fillTableNguoiDung(ndDao.searchByName(txtTimNguoiDung.getText()));

            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnTimNguoiDungActionPerformed

    private void btnMoMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoMayActionPerformed
        index = tblMayTram.getSelectedRow();
        if (index >= 0) {
            if (MessDiaLogHelper.showConfirmDiaLog(this, "Bạn muốn mở " + getMa(index, tblMayTram), "Xác nhận") == 0) {
                try {

                    qlmDao.MoMay(getMa(index, tblMayTram), "admin");
                    fillTableMayTram(qlmDao.selectAll());

                    nkhtDao.insert(getMa(index, tblMayTram), "admin", "ĐANG ONLINE");
                    fillTableNkht(nkhtDao.selectAll());

                    nktkDao.insert(getTenDn(index));
                    fillTableNktk(nktkDao.selectAll());
                } catch (Exception e) {
                    e.printStackTrace();
                    MessDiaLogHelper.showMessDiaLog(this, "Mở máy không thành công", "Thông báo");
                }
            }
        } else {
            MessDiaLogHelper.showMessDiaLog(this, "Bạn cần chọn một máy trong bảng để mở", "Thông báo");
        }
    }//GEN-LAST:event_btnMoMayActionPerformed

    private void btnTatMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTatMayActionPerformed
        index = tblMayTram.getSelectedRow();
        if (index >= 0) {
            if (MessDiaLogHelper.showConfirmDiaLog(this, "Bạn muốn tắt " + getMa(index, tblMayTram), "Xác nhận") == 0) {
                try {
                    qlmDao.TatMay(getMa(index, tblMayTram));
                    fillTableMayTram(qlmDao.selectAll());

                    nkhtDao.insert(getMa(index, tblMayTram), "admin", "ĐANG OFFINE");
                    fillTableNkht(nkhtDao.selectAll());

                    nktkDao.update("admin");
                    fillTableNktk(nktkDao.selectAll());
                } catch (Exception e) {
                    e.printStackTrace();
                    MessDiaLogHelper.showMessDiaLog(this, "Tắt máy không thành công", "Thông báo");
                }
            }
        } else {
            MessDiaLogHelper.showMessDiaLog(this, "Bạn cần chọn một máy trong bảng để tắt", "Thông báo");
        }
    }//GEN-LAST:event_btnTatMayActionPerformed

    private void btnRefreshDvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshDvActionPerformed
        try {
            fillTableDichVu(dvDao.selectAll());
        } catch (Exception ex) {
            ex.printStackTrace();
            MessDiaLogHelper.showErrorDiaLog(this, "Lỗi truy vấn", "Lỗi");
        }
    }//GEN-LAST:event_btnRefreshDvActionPerformed

    private void mniMayTramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniMayTramActionPerformed
        tabs.setSelectedIndex(0);
    }//GEN-LAST:event_mniMayTramActionPerformed

    private void mniNkhtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNkhtActionPerformed
        tabs.setSelectedIndex(2);
    }//GEN-LAST:event_mniNkhtActionPerformed

    private void mniNktkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNktkActionPerformed
        tabs.setSelectedIndex(2);

    }//GEN-LAST:event_mniNktkActionPerformed

    private void btnXoaNkhtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNkhtActionPerformed
        index = tblNkht.getSelectedRow();
        try {
            if (MessDiaLogHelper.showConfirmDiaLog(this, "Bạn có muốn xoá toàn bộ nhật kí hệ thống?", "Xác nhận") == 1) {
                return;
            }
            nkhtDao.delete();
            fillTableNkht(nkhtDao.selectAll());
        } catch (Exception e) {
            e.printStackTrace();
            MessDiaLogHelper.showErrorDiaLog(this, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnXoaNkhtActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        try {
            if (txtTimDv == null) {
                fillTableNkht(nkhtDao.selectAll());

            } else {
                fillTableNkht(nkhtDao.searchByName(txtTimDv.getText()));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void btnNapTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNapTienActionPerformed
        index = tblMayTram.getSelectedRow();
        if (index >= 0) {
            float tien = 0;
            
            try {
                tien = Float.parseFloat(MessDiaLogHelper.showInputDiaLog(this, "Nhập số tiền bạn muốn nạp cho tài khoản " + getTenDn(index), "Input"));
            } catch (Exception e) {
                MessDiaLogHelper.showMessDiaLog(this, "Bạn phải nhập vào định dạng số", "Thông báo");
            }
            
            if (tien > 0) {
                try {

                    ndDao.napTien("admin", tien);
                    ndDao.tongThoiGian("admin");
                    fillTableNguoiDung(ndDao.selectAll());
                    MessDiaLogHelper.showMessDiaLog(this, "Nạp tiền thành công vào tài khoản admin", "Thông báo");
                } catch (Exception e) {
                    e.printStackTrace();
                    MessDiaLogHelper.showMessDiaLog(this, "Nạp tiền thất bại", "Thông báo");
                }

            }
        } else {
            MessDiaLogHelper.showMessDiaLog(this, "Bạn cần chọn một máy trong bảng để nạp tiền", "Thông báo");
        }
    }//GEN-LAST:event_btnNapTienActionPerformed

    private void btnRefreshNkhtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshNkhtActionPerformed
        try {
            if (txtNgayBdNkht == null) {
                fillTableNkht(nkhtDao.selectAll());

            } else {
                fillTableNkht(nkhtDao.searchByDay(txtNgayBdNkht.getText(), txtNgayKtNkht.getText()));

            }
        } catch (Exception ex) {
            ex.printStackTrace();
            MessDiaLogHelper.showMessDiaLog(this, "Không tìm thấy kết quả", "Thông báo");
        }
    }//GEN-LAST:event_btnRefreshNkhtActionPerformed

    private void btnXoaNktkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNktkActionPerformed
        index = tblNkht.getSelectedRow();
        try {
            if (MessDiaLogHelper.showConfirmDiaLog(this, "Bạn có muốn xoá toàn bộ nhật kí tài khoản?", "Xác nhận") == 1) {
                return;
            }
            nktkDao.delete();
            fillTableNktk(nktkDao.selectAll());
        } catch (Exception e) {
            e.printStackTrace();
            MessDiaLogHelper.showErrorDiaLog(this, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnXoaNktkActionPerformed

    private void btnHoanThanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoanThanhActionPerformed
        try {
            index = tblDonHang.getSelectedRow();
            HoaDonChiTietDao dao = new HoaDonChiTietDao();
            dao.capNhatTrangThai(getMa(index, tblDonHang), "HOÀN THÀNH");
            fillTblDonHang();
        } catch (Exception ex) {
            MessDiaLogHelper.showMessDiaLog(this, "Lỗi", "Thông báo");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnHoanThanhActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        try {
            logOff();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_mniDangXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Admin().setVisible(true);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHoanThanh;
    private javax.swing.JButton btnMoMay;
    private javax.swing.JButton btnNapTien;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRefreshDv;
    private javax.swing.JButton btnRefreshNkht;
    private javax.swing.JButton btnRefreshNktk;
    private javax.swing.JButton btnSuaDv;
    private javax.swing.JButton btnSuaNguoiDung;
    private javax.swing.JButton btnTatMay;
    private javax.swing.JButton btnThemDv;
    private javax.swing.JButton btnThemNguoiDung;
    private javax.swing.JButton btnTimDv;
    private javax.swing.JButton btnTimNguoiDung;
    private javax.swing.JButton btnTinhTien;
    private javax.swing.JButton btnXoaDv;
    private javax.swing.JButton btnXoaNguoiDung;
    private javax.swing.JButton btnXoaNkht;
    private javax.swing.JButton btnXoaNktk;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniGioiThieu;
    private javax.swing.JMenuItem mniMayTram;
    private javax.swing.JMenuItem mniNkht;
    private javax.swing.JMenuItem mniNktk;
    private javax.swing.JMenuItem mniTaiKhoan;
    private javax.swing.JMenuItem mniTroGiup;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblDichVu;
    private javax.swing.JTable tblDonHang;
    private javax.swing.JTable tblMayTram;
    private javax.swing.JTable tblNguoiDung;
    private javax.swing.JTable tblNkht;
    private javax.swing.JTable tblNktk;
    private javax.swing.JTextField txtNgayBdNkht;
    private javax.swing.JTextField txtNgayBdNktk;
    private javax.swing.JTextField txtNgayKtNkht;
    private javax.swing.JTextField txtNgayKtNktk;
    private javax.swing.JTextField txtTimDv;
    private javax.swing.JTextField txtTimNguoiDung;
    // End of variables declaration//GEN-END:variables

//    ==================
    DefaultTableModel dvModel, ndModel, nktkModel, mtModel, nkhtModel, dhModel;
    int index;
    DichVuDao dvDao = new DichVuDao();
    NguoiDungDao ndDao = new NguoiDungDao();
    QuanLyMayDao qlmDao = new QuanLyMayDao();
    NhatKiHeThongDao nkhtDao = new NhatKiHeThongDao();
    NhatKiTaiKhoanDao nktkDao = new NhatKiTaiKhoanDao();

    void init() throws Exception {
        initIconTabs();

        initTableNguoiDung();
        fillTableNguoiDung(ndDao.selectAll());

        initTableNktk();
        fillTableNktk(nktkDao.selectAll());

        initTableDichVu();
        fillTableDichVu(dvDao.selectAll());

        initTableMayTram();
        fillTableMayTram(qlmDao.selectAll());

        initTableNkht();
        fillTableNkht(nkhtDao.selectAll());

        initTblDonHang();
        fillTblDonHang();
    }

    void initIconTabs() {
        tabs.setIconAt(0, new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\computer.png"));
        tabs.setIconAt(1, new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\user.png"));
        tabs.setIconAt(2, new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\software.png"));
        tabs.setIconAt(3, new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\users.png"));
        tabs.setIconAt(4, new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Full basket.png"));
        tabs.setIconAt(5, new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\basket.png"));
    }

    private void initTableNguoiDung() {
        ndModel = new DefaultTableModel();
        ndModel.setColumnIdentifiers(new String[]{"TenDN", "Họ và tên", "Giới tính",
            "Số ĐTH", "NgayTao", "Tổng tiền", "Tổng thời gian"});
        tblNguoiDung.setModel(ndModel);
    }

    public void fillTableNguoiDung(List<NguoiDung> list) {
        try {
            ndModel.setRowCount(0);
            for (NguoiDung nd : list) {
                Object[] row = {
                    nd.getTenDN(), nd.getHoTen(),
                    nd.isGioiTinh() ? "Nam" : "Nữ", nd.getSoDth(), nd.getNgayTaoTk(),
                    nd.getTongTien(), nd.getTongThoiGian()
                };
                ndModel.addRow(row);
                ndModel.fireTableDataChanged();
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessDiaLogHelper.showMessDiaLog(this, "Lỗi truy vấn dữ liệu", "Thông báo");
        }
    }

    private void initTableNktk() {
        nktkModel = new DefaultTableModel();
        nktkModel.setColumnIdentifiers(new String[]{"TenDN", "Ngày chơi", "Giờ bắt đầu",
            "Giờ kết thúc", "Ghi chú"});
        tblNktk.setModel(nktkModel);
    }

    public void fillTableNktk(List<NhatKiTaiKhoan> list) {
        try {
            nktkModel.setRowCount(0);
            for (NhatKiTaiKhoan nktk : list) {
                Object[] row = {
                    nktk.getTenDN(), nktk.getNgay(), nktk.getGioBatDau(),
                    nktk.getGioKetThuc(), nktk.getGhiChu()
                };
                nktkModel.addRow(row);
                nktkModel.fireTableDataChanged();
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessDiaLogHelper.showMessDiaLog(this, "Lỗi truy vấn dữ liệu", "Thông báo");
        }
    }

    private void initTableDichVu() {
        dvModel = new DefaultTableModel();
        dvModel.setColumnIdentifiers(new String[]{"Mã dịch vụ", "Tên dịch vụ", "Giá",
            "Hình", "Trạng thái", "Người tạo", "Ngày tạo"});
        tblDichVu.setModel(dvModel);
    }

    public void fillTableDichVu(List<DichVu> list) {
        try {
            dvModel.setRowCount(0);
            for (DichVu dv : list) {
                Object[] row = {
                    dv.getMaDV(), dv.getTenDV(), dv.getGia(),
                    dv.getHinh(), dv.getTrangThai(),
                    dv.getNguoiTao(), dv.getNgayTao()
                };
                dvModel.addRow(row);
                dvModel.fireTableDataChanged();
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessDiaLogHelper.showMessDiaLog(this, "Lỗi truy vấn dữ liệu", "Thông báo");
        }
    }

    private void initTableMayTram() {
        mtModel = new DefaultTableModel();
        mtModel.setColumnIdentifiers(
                new String[]{"Tên máy", "Người sử dụng", "Trạng thái", "Ghi chú"}
        );
        tblMayTram.setModel(mtModel);
    }

    public void fillTableMayTram(List<QuanLyMay> list) {
        try {
            mtModel.setRowCount(0);
            for (QuanLyMay qlm : list) {
                Object[] row = {
                    qlm.getTenMay(), qlm.getNguoiSuDung(), qlm.getTinhTrang(), qlm.getGhiChu()
                };
                mtModel.addRow(row);
                mtModel.fireTableDataChanged();
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessDiaLogHelper.showMessDiaLog(this, "Lỗi truy vấn dữ liệu", "Thông báo");
        }
    }

    private void initTableNkht() {
        nkhtModel = new DefaultTableModel();
        nkhtModel.setColumnIdentifiers(
                new String[]{"Tên máy", "Người sử dụng", "Ngày", "Thời gian", "Trạng thái", "Ghi chú"}
        );
        tblNkht.setModel(nkhtModel);
    }

    public void fillTableNkht(List<NhatKiHeThong> list) {
        try {
            nkhtModel.setRowCount(0);
            for (NhatKiHeThong nkht : list) {
                Object[] row = {
                    nkht.getTenMay(), nkht.getTenNguoiSuDung(), nkht.getNgay(),
                    nkht.getThoiGian(), nkht.getTrangThai(), nkht.getGhiChu()
                };
                nkhtModel.addRow(row);
                nkhtModel.fireTableDataChanged();
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessDiaLogHelper.showMessDiaLog(this, "Lỗi truy vấn dữ liệu", "Thông báo");
        }
    }

    public void initTblDonHang() {
        dhModel = new DefaultTableModel();
        dhModel.setColumnIdentifiers(new String[]{"Mã hoá đơn", "Mã dịch vụ", "Tên dịch vụ", "Người order", "Giá", "Số lượng", "Trạng thái"});
        tblDonHang.setModel(dhModel);

    }

    public void fillTblDonHang() {
        try {
            dhModel.setRowCount(0);

            HoaDonChiTietDao dao = new HoaDonChiTietDao();
            List<HoaDonChiTiet> list = dao.selectAll();
            for (HoaDonChiTiet hdct : list) {
                Object[] row = {
                    hdct.getMaHD(), hdct.getMaDV(), hdct.getTenDV(), hdct.getTenDn(),
                    hdct.getGia(), hdct.getSoLuong(), hdct.getTrangThai()
                };
                dhModel.addRow(row);
                dhModel.fireTableDataChanged();
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessDiaLogHelper.showMessDiaLog(this, "Lỗi truy vấn dữ liệu", "Thông báo");
        }
    }

    String getMa(int index, JTable tableName) {
        try {
            String ma = (String) tableName.getValueAt(index, 0);
            return ma;
        } catch (Exception e) {
            return null;
        }
    }

    public String getTenDn(int index) {
        try {
            String tenDn = (String) tblMayTram.getValueAt(index, 1);
            return tenDn;
        } catch (Exception e) {
            return null;
        }
    }

    void logOff() throws Exception {
        Auth.clear();
        this.setVisible(false);
        new DangNhapDiaLog(this, true).setVisible(true);

    }
}
