// Hìdv 172,162
package Dialog;

import Dao.DichVuDao;
import Data.DichVu;
import Library.MessDiaLogHelper;
import Library.More;
import Library.Validator;
import Library.XDate;
import Library.XImage;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author Admin
 */
public class DichVuAdminDialog extends javax.swing.JDialog {

    /**
     * Creates new form ThemTaiKhoan
     */
    public DichVuAdminDialog(java.awt.Frame parent, boolean modal, boolean isupdate) {
        super(parent, modal);
        initComponents();
        this.isUpdate=isupdate;
        
        initData();
    }
    
    public DichVuAdminDialog(java.awt.Frame parent, boolean modal, boolean isupdate, String maDv) {
        super(parent, modal);
        initComponents();
        this.isUpdate=isupdate;
        this.maDv=maDv;
        
        initData();
        fillToForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTieuDe = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaDv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenDv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNguoiTao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNgayTao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        cboTrangThai = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTieuDe.setText("Thêm dịch vụ");

        jLabel2.setText("Mã dịch vụ:");

        jLabel3.setText("Tên dịch vụ:");

        jLabel4.setText("Giá");

        jLabel5.setText("Trạng thái:");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImg.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\image.png")); // NOI18N
        lblImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImgMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel7.setText("Người tạo:");

        txtNguoiTao.setEditable(false);

        jLabel8.setText("Ngày tạo:");

        txtNgayTao.setEditable(false);

        jLabel9.setText("Hình ảnh:");

        btnThoat.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\Delete.png")); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnOk.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\create.png")); // NOI18N
        btnOk.setText("Thêm");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Còn", "Hết" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTieuDe)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 182, Short.MAX_VALUE)
                                .addComponent(btnOk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnThoat))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(txtGia)
                                        .addComponent(txtMaDv))
                                    .addComponent(jLabel9))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(txtTenDv, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtNguoiTao, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtNgayTao, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(cboTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(12, 12, 12))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTieuDe)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenDv)
                    .addComponent(txtMaDv))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(txtNguoiTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoat)
                    .addComponent(btnOk))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if (!Validator.isNumber(this, txtGia.getText())) {
            txtGia.setBackground(Color.yellow);
            return;
        }
        try {
            if (dao.selectById(txtMaDv.getText()) != null) {
                if (MessDiaLogHelper.showConfirmDiaLog(this, "Bạn có muốn cập nhật?", "Xác nhận") == 1) {
                    return;
                }
                update();
            } else {
                insert();
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessDiaLogHelper.showErrorDiaLog(this, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private byte[] personalImg;
    private void lblImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgMouseClicked
        JFileChooser chooser = new JFileChooser();

        chooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                } else {
                    return f.getName().toLowerCase().endsWith(".jpg");
                }
            }

            @Override
            public String getDescription() {
                return "Image File (*.jpg)";
            }
        });
        if (chooser.showOpenDialog(this) == 1) {
            return;
        }
        File file = chooser.getSelectedFile();
        try {
            ImageIcon icon = new ImageIcon(file.getPath());
            Image img = XImage.resize(icon.getImage(), 174, 210);
            ImageIcon resizedIcon = new ImageIcon(img);
            lblImg.setIcon(resizedIcon);
            personalImg = XImage.toByteArray(img, "jpg");
        } catch (Exception e) {
            e.printStackTrace();
            MessDiaLogHelper.showErrorDiaLog(this, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_lblImgMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DichVuAdminDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DichVuAdminDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DichVuAdminDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DichVuAdminDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DichVuAdminDialog dialog = new DichVuAdminDialog(new javax.swing.JFrame(), true, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaDv;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtNguoiTao;
    private javax.swing.JTextField txtTenDv;
    // End of variables declaration//GEN-END:variables

    DichVuDao dao = new DichVuDao();
    boolean isUpdate;
    int index;
    String maDv;

    void initData(){
        More.jdialogAdd(this, null);
            txtNguoiTao.setText("thanhngubo");
            
            long millis = System.currentTimeMillis();            
            java.sql.Date date = new java.sql.Date(millis);
            txtNgayTao.setText("" + date);
            
        if (isUpdate) {
            lblTieuDe.setText("Cập nhật dịch vụ");
            txtMaDv.setEditable(false);
            txtNguoiTao.setEditable(true);
            txtNgayTao.setEditable(true);
            btnOk.setText("Cập nhật");
            btnOk.setIcon(new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\update.png"));

        }
    }
    
    DichVu getModel() {
        DichVu dv = new DichVu();

        dv.setMaDV(txtMaDv.getText());
        dv.setTenDV(txtTenDv.getText());
        dv.setGia(Float.parseFloat(txtGia.getText()));
        
        Date date = XDate.toDate(txtNgayTao.getText(), "yyyy-MM-dd");
        java.sql.Date sqlDate = new java.sql.Date(date.getTime());
        dv.setNgayTao(sqlDate);
        
        dv.setNguoiTao(txtNguoiTao.getText());
        dv.setTrangThai(cboTrangThai.getSelectedItem().toString());
        dv.setHinh(personalImg);

        return dv;
    }
    
    void setModel(DichVu model) {
        txtMaDv.setText(model.getMaDV());
        txtTenDv.setText(model.getTenDV());
        txtGia.setText("" + model.getGia());
        txtNguoiTao.setText("" + model.getNguoiTao());
        try {
            if (model.getHinh() != null) {
                Image img = XImage.createImgFromByteArray(model.getHinh(), "jpg");
                lblImg.setIcon(new ImageIcon(img));
                personalImg = model.getHinh();
            } else {
                ImageIcon icon = new javax.swing.ImageIcon("D:\\DA_JAVA_1\\DA_1\\src\\main\\java\\Icons\\image.png");
                lblImg.setIcon(icon);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        txtNgayTao.setText(""+model.getNgayTao());
        if (model.getTrangThai().equalsIgnoreCase("Còn")) {
            cboTrangThai.setSelectedIndex(0);
        } else {
            cboTrangThai.setSelectedIndex(1);

        }
    }
    
    
    void insert() {
        DichVu dv = getModel();

        try {
            dao.insert(dv);
//            this.fillTable();
//            this.clear();
            MessDiaLogHelper.showMessDiaLog(this, "Thêm mới thành công", "Thông báo");
        } catch (Exception e) {
            e.printStackTrace();
            MessDiaLogHelper.showMessDiaLog(this, "Thêm mới thất bại", "Thông báo");
        }
    }

    void update() {
        DichVu dv = getModel();
        try {
            dao.update(dv);
            MessDiaLogHelper.showMessDiaLog(this, "Cập nhật thành công", "Thông báo");
        } catch (Exception e) {
            MessDiaLogHelper.showMessDiaLog(this, "Cập nhật thất bại", "Thông báo");

        }
    }
    
    void fillToForm(){
        
        try {
            DichVu dv = dao.selectById(maDv);
            setModel(dv);
        } catch (Exception ex) {
            ex.printStackTrace();
            MessDiaLogHelper.showErrorDiaLog(this, "Lỗi truy vấn", "Lỗi");
        }
    }
}
